### ISSUE TITLE
Check the image actually exists before creating the PR

### ISSUE THREAD

**Issue by juanjosevazquezgil** [prefapp/action-make-state-repos-dispatches#5]
# Motivation
When using this workflow to make a dispatch, the image name and URL location is constructed using external inputs, and then a PR is either created or updated with these values on the state repo. Before doing this, in case some input was misplaced or some value misconstructed, we would like the action to check whether the image exists at the URL. If it does, the PR is created normally. If not, it should throw an error and halt execution

### Acceptance criteria
- [x] The workflow checks whether the image exists at the URL it calculated
- [x] The workflow creates a PR when it does
- [x] The workflow throws an error when it doesn't
- [ ] Team acceptance

**Comment by jalvarezit** [comment]
I believe that the best way to handle it would be to add extra steps before calling the action to login in the provider. Therefore in the action we assume we are logged in the given registries. After that we only need to do something among the lines of "docker search <image-name>" and throw an error if not found as explained before.
